all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      dsn: 'mysql:host=localhost;dbname=surrogate_webadmin'
      username: root
      password: null
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8
      